const fallbackData = {
  categories: [
    { id: "coffee", name: "Cà phê", icon: "bi-cup-hot-fill", description: "Hạt cà phê đậm vị cao nguyên" },
    { id: "nuts", name: "Mắc ca", icon: "bi-brightness-alt-high-fill", description: "Béo bùi, tiện dùng mỗi ngày" },
    { id: "honey", name: "Mật ong", icon: "bi-flower1", description: "Ngọt thanh từ mùa hoa rừng" },
    { id: "durian", name: "Sầu riêng", icon: "bi-stars", description: "Hương vị Krông Pắc theo mùa" },
    { id: "pepper", name: "Tiêu", icon: "bi-fire", description: "Cay ấm, thơm rõ từng hạt" },
    { id: "dry", name: "Đặc sản khô", icon: "bi-basket2-fill", description: "Dễ bảo quản, đậm vị vùng cao" },
    { id: "gift", name: "Quà tặng", icon: "bi-gift-fill", description: "Gói trọn câu chuyện Tây Nguyên" },
  ],
  products: [
    {
      id: 1,
      slug: "ca-phe-rang-moc-buon-ma-thuot",
      name: "Cà phê rang mộc Buôn Ma Thuột",
      category: "coffee",
      categoryName: "Cà phê",
      price: 189000,
      compareAtPrice: 219000,
      badge: "Bán chạy",
      rating: 4.9,
      reviewCount: 128,
      image: "assets/product-coffee.jpg",
      description: "Robusta rang mộc vị đậm, hậu ngọt, hợp pha phin hoặc máy.",
      origin: "Buôn Ma Thuột, Đắk Lắk",
      weight: "500g",
      stock: 42,
      featured: true,
    },
    {
      id: 2,
      slug: "arabica-cau-dat-rang-vua",
      name: "Arabica Cầu Đất rang vừa",
      category: "coffee",
      categoryName: "Cà phê",
      price: 225000,
      compareAtPrice: 255000,
      badge: "Hương hoa quả",
      rating: 4.8,
      reviewCount: 74,
      image: "assets/product-coffee-honey.jpg",
      description: "Hương cam chín và caramel nhẹ, cân bằng cho pha thủ công.",
      origin: "Cầu Đất, Lâm Đồng",
      weight: "340g",
      stock: 28,
      featured: true,
    },
    {
      id: 3,
      slug: "mac-ca-dak-lak-rang-moc",
      name: "Mắc ca Đắk Lắk rang mộc",
      category: "nuts",
      categoryName: "Mắc ca",
      price: 165000,
      compareAtPrice: 185000,
      badge: "Mới về",
      rating: 4.9,
      reviewCount: 93,
      image: "assets/product-macadamia.jpg",
      description: "Hạt béo bùi, tách vỏ tiện dụng, không phụ gia.",
      origin: "Ea H'leo, Đắk Lắk",
      weight: "250g",
      stock: 36,
      featured: true,
    },
    {
      id: 4,
      slug: "mat-ong-hoa-ca-phe",
      name: "Mật ong hoa cà phê",
      category: "honey",
      categoryName: "Mật ong",
      price: 220000,
      compareAtPrice: null,
      badge: "Theo mùa",
      rating: 4.9,
      reviewCount: 81,
      image: "assets/product-honey.jpg",
      description: "Mật ngọt thanh, thơm dịu, dùng pha trà hoặc làm quà.",
      origin: "Cư M'gar, Đắk Lắk",
      weight: "500ml",
      stock: 23,
      featured: true,
    },
    {
      id: 5,
      slug: "tieu-den-dak-nong",
      name: "Tiêu đen Đắk Nông tuyển hạt",
      category: "pepper",
      categoryName: "Tiêu",
      price: 99000,
      compareAtPrice: null,
      badge: "Đậm vị",
      rating: 4.8,
      reviewCount: 66,
      image: "assets/product-pepper.jpg",
      description: "Tiêu hạt thơm ấm, phù hợp cho căn bếp hằng ngày.",
      origin: "Đắk Song, Đắk Nông",
      weight: "200g",
      stock: 54,
      featured: false,
    },
    {
      id: 6,
      slug: "mang-kho-gia-lai",
      name: "Măng khô Gia Lai",
      category: "dry",
      categoryName: "Đặc sản khô",
      price: 129000,
      compareAtPrice: 145000,
      badge: "Đặc sản vùng",
      rating: 4.7,
      reviewCount: 42,
      image: "assets/product-dried.jpg",
      description: "Măng khô thơm, dễ bảo quản cho món canh và món hầm.",
      origin: "Kbang, Gia Lai",
      weight: "300g",
      stock: 31,
      featured: false,
    },
    {
      id: 7,
      slug: "bo-mot-nang-muoi-kien-vang",
      name: "Bò một nắng muối kiến vàng",
      category: "dry",
      categoryName: "Đặc sản khô",
      price: 319000,
      compareAtPrice: 349000,
      badge: "Quà vùng cao",
      rating: 4.9,
      reviewCount: 57,
      image: "assets/product-beef.jpg",
      description: "Đặc sản khô đậm đà, gợi ý dùng cùng muối kiến vàng.",
      origin: "Krông Pa, Gia Lai",
      weight: "300g",
      stock: 16,
      featured: false,
    },
    {
      id: 8,
      slug: "combo-qua-tang-dai-ngan",
      name: "Combo quà tặng Đại Ngàn",
      category: "gift",
      categoryName: "Quà tặng",
      price: 499000,
      compareAtPrice: 565000,
      badge: "Gói quà sẵn",
      rating: 5,
      reviewCount: 46,
      image: "assets/product-gift.jpg",
      description: "Hộp quà gồm cà phê, mắc ca, mật ong và tiêu tuyển chọn.",
      origin: "Tây Nguyên",
      weight: "01 hộp",
      stock: 19,
      featured: true,
    },
    {
      id: 9,
      slug: "sau-rieng-say-lanh-krong-pac",
      name: "Sầu riêng sấy lạnh Krông Pắc",
      category: "durian",
      categoryName: "Sầu riêng",
      price: 235000,
      compareAtPrice: 265000,
      badge: "Đúng mùa",
      rating: 4.9,
      reviewCount: 69,
      image: "assets/product-durian.jpg",
      description: "Miếng sầu riêng sấy lạnh thơm béo, giữ trọn vị trái cây chín.",
      origin: "Krông Pắc, Đắk Lắk",
      weight: "200g",
      stock: 24,
      featured: true,
    },
    {
      id: 10,
      slug: "ca-phe-honey-process-cau-dat",
      name: "Cà phê Honey Process Cầu Đất",
      category: "coffee",
      categoryName: "Cà phê",
      price: 269000,
      compareAtPrice: 299000,
      badge: "Tuyển chọn",
      rating: 4.9,
      reviewCount: 51,
      image: "assets/product-coffee-honey.jpg",
      description: "Sơ chế mật ong cho hương ngọt trái cây và hậu vị mượt mà.",
      origin: "Cầu Đất, Lâm Đồng",
      weight: "250g",
      stock: 18,
      featured: true,
    },
    {
      id: 11,
      slug: "mat-ong-rung-tay-nguyen",
      name: "Mật ong rừng Tây Nguyên",
      category: "honey",
      categoryName: "Mật ong",
      price: 245000,
      compareAtPrice: 275000,
      badge: "Nguyên chất",
      rating: 4.8,
      reviewCount: 88,
      image: "assets/product-honey.jpg",
      description: "Mật ong rừng hương đậm, phù hợp pha nước ấm và làm quà.",
      origin: "Chư Păh, Gia Lai",
      weight: "500ml",
      stock: 22,
      featured: true,
    },
  ],
  posts: [
    {
      id: 1,
      slug: "ca-phe-buon-ma-thuot-co-gi-dac-biet",
      title: "Cà phê Buôn Ma Thuột có gì đặc biệt?",
      tag: "Cà phê Tây Nguyên",
      image: "assets/product-coffee.jpg",
      excerpt: "Từ độ cao, thổ nhưỡng đến kiểu rang, cùng khám phá lý do hạt cà phê vùng này có hậu vị riêng.",
      readTime: 6,
      publishedAt: "2026-08-10",
    },
    {
      id: 2,
      slug: "dac-san-tay-nguyen-lam-qua",
      title: "Đặc sản Tây Nguyên làm quà: chọn gì cho tinh tế?",
      tag: "Cẩm nang mua đặc sản",
      image: "assets/product-gift.jpg",
      excerpt: "Gợi ý cách chọn quà theo dịp, người nhận và ngân sách để hộp quà có câu chuyện hơn.",
      readTime: 5,
      publishedAt: "2026-08-07",
    },
    {
      id: 3,
      slug: "mac-ca-dak-lak-tu-hat-den-qua-tang",
      title: "Mắc ca Đắk Lắk: từ hạt béo bùi đến món quà sức khỏe",
      tag: "Kiến thức sản phẩm",
      image: "assets/product-macadamia.jpg",
      excerpt: "Mẹo chọn hạt, bảo quản và sử dụng mắc ca để giữ được độ giòn thơm tự nhiên.",
      readTime: 4,
      publishedAt: "2026-08-03",
    },
  ],
};

window.TNF_FALLBACK_DATA = fallbackData;
